name: tbtg

version: "3.8"
services:
  postgres:
    image: postgres:17.2
    container_name: tbtg-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tbtg-vouchers-clients
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
